#!/usr/bin/env tsx
/**
 * Generate a Move integration test covering every circuit in vk_data.json.
 * For each circuit:
 *   - run snarkjs fullProve with its circuits/<name>/input.json
 *   - confirm local verify passes
 *   - serialize proof + public inputs to Arkworks canonical compressed bytes
 *   - emit a Move test that registers the VK and calls verify_proof_static
 *
 * Output is written to sui-groth16-verifier/tests/all_circuits_tests.move.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import * as snarkjs from 'snarkjs';

import {
  convertProofForSui,
  convertPublicInputsForSui,
  convertVKForSui,
  bytesToHex,
} from '../../lib/sui/converter';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(__dirname, '..', '..');

interface CircuitMeta {
  templateId: number;
  name: string;
  nPublic: number;
}

async function buildFixture(meta: CircuitMeta) {
  const wasm = join(REPO_ROOT, `public/circuits/${meta.name}.wasm`);
  const zkey = join(REPO_ROOT, `public/circuits/${meta.name}.zkey`);
  const vkPath = join(REPO_ROOT, `public/circuits/${meta.name}_vkey.json`);
  const inputPath = join(REPO_ROOT, `circuits/${meta.name}/input.json`);

  for (const p of [wasm, zkey, vkPath, inputPath]) {
    if (!existsSync(p)) {
      return { meta, skipped: `missing ${p}` };
    }
  }

  const vk = JSON.parse(readFileSync(vkPath, 'utf8'));
  const input = JSON.parse(readFileSync(inputPath, 'utf8'));

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    input,
    wasm,
    zkey,
  );

  const localOk = await snarkjs.groth16.verify(vk, publicSignals, proof);
  if (!localOk) {
    return { meta, skipped: 'snarkjs local verify failed' };
  }

  const { vkBytes, nPublic } = convertVKForSui(vk);
  if (nPublic !== meta.nPublic) {
    return {
      meta,
      skipped: `vk.nPublic=${nPublic} mismatches vk_data.json nPublic=${meta.nPublic}`,
    };
  }

  const { proofPointsBytes } = convertProofForSui(proof);
  const publicInputsBytes = convertPublicInputsForSui(publicSignals);

  return {
    meta,
    skipped: null,
    vkHex: bytesToHex(vkBytes),
    proofHex: bytesToHex(proofPointsBytes),
    inputsHex: bytesToHex(publicInputsBytes),
    nPublic,
  };
}

function sanitizeId(name: string) {
  return name.replace(/-/g, '_');
}

function renderMoveTest(results: Awaited<ReturnType<typeof buildFixture>>[]) {
  const used = results.filter((r) => !r.skipped);

  const header = `// Auto-generated by scripts/sui/generate-all-fixtures.ts
// Do NOT edit by hand — rerun the generator to refresh.

#[test_only]
module zkrune::all_circuits_tests {
    use sui::test_scenario;
    use zkrune::groth16_verifier::{Self, AdminCap, VerifierRegistry};

    const ADMIN: address = @0xAD;

`;

  const body = used
    .map((r) => {
      const id = sanitizeId(r.meta.name);
      const idUpper = id.toUpperCase();
      return `    const ${idUpper}_VK: vector<u8> = x"${r.vkHex}";
    const ${idUpper}_PROOF: vector<u8> = x"${r.proofHex}";
    const ${idUpper}_INPUTS: vector<u8> = x"${r.inputsHex}";

    #[test]
    fun test_${id}_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                ${r.meta.templateId},
                b"${r.meta.name}",
                ${idUpper}_VK,
                ${r.nPublic},
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, ${r.meta.templateId}, ${idUpper}_PROOF, ${idUpper}_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }
`;
    })
    .join('\n');

  return header + body + '}\n';
}

async function main() {
  const vkDataPath = join(REPO_ROOT, 'sui-groth16-verifier/vk_data.json');
  const circuits: CircuitMeta[] = JSON.parse(readFileSync(vkDataPath, 'utf8'));

  console.log(`Building fixtures for ${circuits.length} circuits...\n`);

  const results = [];
  for (const meta of circuits) {
    process.stdout.write(`  [${meta.templateId}] ${meta.name.padEnd(24)} `);
    try {
      const r = await buildFixture(meta);
      if (r.skipped) {
        console.log(`SKIP (${r.skipped})`);
      } else {
        console.log(`OK  (proof=${r.proofHex.length / 2}B, inputs=${r.inputsHex.length / 2}B)`);
      }
      results.push(r);
    } catch (e: any) {
      console.log(`ERR (${e.message})`);
      results.push({ meta, skipped: e.message });
    }
  }

  const used = results.filter((r) => !r.skipped);
  const skipped = results.filter((r) => r.skipped);

  console.log(`\nGenerated fixtures: ${used.length}/${circuits.length}`);
  if (skipped.length > 0) {
    console.log('Skipped:');
    skipped.forEach((r) => console.log(`  - ${r.meta.name}: ${r.skipped}`));
  }

  const outPath = join(
    REPO_ROOT,
    'sui-groth16-verifier/tests/all_circuits_tests.move',
  );
  writeFileSync(outPath, renderMoveTest(results));
  console.log(`\nWrote ${outPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
