// Auto-generated by scripts/sui/generate-all-fixtures.ts
// Do NOT edit by hand — rerun the generator to refresh.

#[test_only]
module zkrune::all_circuits_tests {
    use sui::test_scenario;
    use zkrune::groth16_verifier::{Self, AdminCap, VerifierRegistry};

    const ADMIN: address = @0xAD;

    const AGE_VERIFICATION_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1904000000000000000ee64b26fff1d081083c8e168bbffaf63d4a14f8f1620e8cf90b0063c9ed93915dd1b63e06adbacea3c6b7b4e247211bff64c5157ef9416c5a5115c1d5fb232daa33aec6b7b81bd6b6c3c3a29b936712397df1e58e8a373b79785a01bbf1e693078bcdf3c983f8964d79fe956d5d0e3a499101d9ea8d496ec2293450250cdd0e";
    const AGE_VERIFICATION_PROOF: vector<u8> = x"48382df55f0ffea8f88d8ee19278e3f903b66fc3ea040dc3b8e1fa8b5d625f8846b45e19b78d4ea540f5e895c385c96bbc24d7c451dd1bc27c78a82e5a39491439fb6f29d1fec91f1f11cd651615943ac0f545164be20020bfd5a35dc72d24ac79ec5a4d6bdae6328a060c384fefd575e204a3b2ff710786d3731a5c2c67e02f";
    const AGE_VERIFICATION_INPUTS: vector<u8> = x"0100000000000000000000000000000000000000000000000000000000000000e9070000000000000000000000000000000000000000000000000000000000001500000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_age_verification_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                0,
                b"age-verification",
                AGE_VERIFICATION_VK,
                3,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 0, AGE_VERIFICATION_PROOF, AGE_VERIFICATION_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const BALANCE_PROOF_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1903000000000000001d6fa9cc43c91b60ae3bae77db90c909892020c78d290b17d5c60f1789868905ba0e533f7b570b9ad40506dddfb4bb66a057c2f4666fd7840e5526c72fb450831b2df98bdf4628e31f2e61272bcfacd54b4787c542b9d727792d76883ba68f82";
    const BALANCE_PROOF_PROOF: vector<u8> = x"9c1b4abc79c6379784ce568dd305278a79d592ece5dec8705c1fa41d1d69f4a8ffb4ce7e9a90a240e1ec49b4d799525c8a8e05c9652d38bdb0e3fc939598ce13db135a9f4376ed3e2759a8298db6cccfca8fa6c526af71ae09f3ad42acb268a53946dee3ab290fedc600e1e6e7214ac8c0d1846437c0db94ae484b3e7c7dc78d";
    const BALANCE_PROOF_INPUTS: vector<u8> = x"0100000000000000000000000000000000000000000000000000000000000000f401000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_balance_proof_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                1,
                b"balance-proof",
                BALANCE_PROOF_VK,
                2,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 1, BALANCE_PROOF_PROOF, BALANCE_PROOF_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const MEMBERSHIP_PROOF_VK: vector<u8> = x"16089f9dbc7a13840b55785b4691804242826600d9cd81586ced01c894139221db0d96c3bacd942724d9261e59c02b587441112f6cb63c9f30ed886df399fa08a1891e84ce2930ea3c30e5d193e3b8248e5d080e8f54a5fee9753d567c6b2a95edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190300000000000000557348db429f36c81e975c894550f301ec029233e9ea4abfa47316ed71bb25888df7d8bb699195a0a0bf922ebee7e6c2c37a2fd1dbc97c34eadd3d9197875316e9168509d309800e03c75b638526256e74fab8e8e8957773be1f66fe0826c698";
    const MEMBERSHIP_PROOF_PROOF: vector<u8> = x"b56599741f97b3f4fbde9c2e63b15ce15c250ec56b371f485a6350453ba2dc9d64d53c4ccd38989fe0b87d8822720a21e4796a3b1f85012b1703cbe173f1bf1a1f6f9084451caafafe7e01a69ab669977820b605cf12bd9d4279287384e9982d765b9a55e6ed94dcc0eb56555a19cd12b823e9fb7982cb1fadab958eca94129a";
    const MEMBERSHIP_PROOF_INPUTS: vector<u8> = x"0100000000000000000000000000000000000000000000000000000000000000fad43555491f12be6c971a2f9322751c03de6bb8042022f76d2eba87a25dca1e";

    #[test]
    fun test_membership_proof_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                2,
                b"membership-proof",
                MEMBERSHIP_PROOF_VK,
                2,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 2, MEMBERSHIP_PROOF_PROOF, MEMBERSHIP_PROOF_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const CREDENTIAL_PROOF_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1904000000000000006b07b841486ddf8bc5dfaedeffde240752ec1d6a29205733e44a1bd9ca5f5da54d2da23199c092e5ed91d37adf769d934ef81650d3ba25e76c7910e1078598af3abeae5aa83dde29f251ad065ddb8e87d2a2bedaafe3411cd861d8c28e199826db94977de1b576e483816d7a331c3ae3204335988bfdea7c083207fe9e44f519";
    const CREDENTIAL_PROOF_PROOF: vector<u8> = x"696555f40c6bf0ec2920de53c0a8a6e2bf992cb65545dc94a664319b0d4bce929d6a9e6df4bb7f4683d9d7819d66bedfd61852672b3cf5e012b5ddeb2688df0a1c2cf5ebbb070e8292f1aff12c3063549662c4ce622f2fd677315c89f2afb90e0d3d738a63bd31cce22c34d836fc03561de9d502db86808f6856242269fcdb1f";
    const CREDENTIAL_PROOF_INPUTS: vector<u8> = x"010000000000000000000000000000000000000000000000000000000000000000f1536500000000000000000000000000000000000000000000000000000000d20a1feb8ca954ab000000000000000000000000000000000000000000000000";

    #[test]
    fun test_credential_proof_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                3,
                b"credential-proof",
                CREDENTIAL_PROOF_VK,
                3,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 3, CREDENTIAL_PROOF_PROOF, CREDENTIAL_PROOF_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const PRIVATE_VOTING_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1903000000000000007c9f366f31aabc3f6c11dde5ba647477bee1ea4e2e14c17adcaeb1b80690c2998e84d8d9ec4e47de285a4f4fbe73c4ad03ca37a71c800a360396b0da38950ba3577111583c074eb570e61c82d093c67ddbde388a60fc58e0c171136669e86c83";
    const PRIVATE_VOTING_PROOF: vector<u8> = x"453c30f741a92b484fe9a33f194acc35cc90570a3dfe9a702dfadea1a4a551a6fd580967c8d834019c79062e3c2bbf44b3c9cb7da95006afe6d178af3c09652e222fe614d452df8c46fd991456e6f3ab813a563077666dbd2e92fd6497ff33806b29938b2127c755a284aa631c1e725676218d8752bccaa6cd77c86eff82a79f";
    const PRIVATE_VOTING_INPUTS: vector<u8> = x"a6993688dc600d2fadf983257ba5475b1f15ca677cdba2656d0da7fed99a1c2c2a00000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_private_voting_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                4,
                b"private-voting",
                PRIVATE_VOTING_VK,
                2,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 4, PRIVATE_VOTING_PROOF, PRIVATE_VOTING_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const NFT_OWNERSHIP_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1906000000000000003d98a0f3d93c1b5cdc8473cb8261e9a0bcc58a9a978417f40580d0ef629c600b0bd40c17a353b160a4369cbac8857fddfcc3b3d6d83359009202099a761837828997860f06a2c7560ae3fa8b298d9f8cb79bb26df90164b81ab49ca34fd294a0c6b0af0d351d74da2bcfac55ec4f4c424dcba08053d21594053562eee620f488ed90f31e6550b951ea7f21db61f5dbaf611b251dbb85895928f50ff4d55421a4542f0797069bc88dc243ef65580c89a84db584a7f8e8b489e8da6340a7d9ed09";
    const NFT_OWNERSHIP_PROOF: vector<u8> = x"4a04e137a72cf17bdb9015b164d66a29a00f021824aa1c7b2cabbbc2098e3d2399ba01575ebb008c28d371db3e6ff9093bb7fb5d6ae8124ebf6cfc7ada70c623224c84f60960d52b07223b82d41871ec4ba80ebb636ffdf7d9f367b0a2ee8221107bcf2aa8c2b6547e80f470a8fcb23dfb7cdc90378f44b6b887d9365efa0ea4";
    const NFT_OWNERSHIP_INPUTS: vector<u8> = x"367949f6145246512b4b1ebf9b6a726bc7ef20a0cff3d42fc6605dd521acea11010000000000000000000000000000000000000000000000000000000000000046906c25ce119c518731e47f546a270bf30cf9cab30dfa33a3172a691505360101000000000000000000000000000000000000000000000000000000000000001027000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_nft_ownership_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                5,
                b"nft-ownership",
                NFT_OWNERSHIP_VK,
                5,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 5, NFT_OWNERSHIP_PROOF, NFT_OWNERSHIP_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const RANGE_PROOF_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e1904000000000000008efa53133debdc36bc250706f1ffd475a5fb6de6b1b4635d06085dbe16ef210ff7e79007723bc57d416f021f18da8a8e5518993a0497e5c5cd4eb2b2e1dbd39b40e4a31479805b1faaffb8d91f24bc5d8986713f7a64266b8a0afcddc1d3c903bb2eea8529647e6e2add332edd983cde0efc60cac7b8a9435e1fd1a41a40c110";
    const RANGE_PROOF_PROOF: vector<u8> = x"42bbdcbe4aba353d90321310a643023bba8914dc409b557d5f9828a2042f482f0e40ba466d30b533a8a78d267360cc5ad640ada15ffcb4b8470116bcb9be89038878ea7365c144d3f8b3d4a50c082091b7e64aafe9965b1b1b002bbbcc7b35a22d9a7444455a994d45153bec26848bc00021806ebb8bdf3f89bd87e45cc0f584";
    const RANGE_PROOF_INPUTS: vector<u8> = x"010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_range_proof_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                6,
                b"range-proof",
                RANGE_PROOF_VK,
                3,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 6, RANGE_PROOF_PROOF, RANGE_PROOF_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const HASH_PREIMAGE_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190400000000000000bee8d5019aabedad9ee29a39892be42fc490d74148b53c598b654d4dbf278b26370ff91056831273bd363b2e7741ffd89a3afef061d9c82bd66f7328ec42d026d918cf1e53b8074a0ade6b12b0b20320b3991bf6f24f527f1d01f773f8e6771986cf7fe62e9343b21cb14b7f7c875c3b4a8dc9cfbd78a01d3825e4b00a99b6af";
    const HASH_PREIMAGE_PROOF: vector<u8> = x"da583bb30546e01512c2af96eae640640fc94b8aef4fb03af9a56a09cd91be830a0091445046fd3c2c4f8e71c586e8dd139a02dcd8c8529e7901477caad776293af6fa94a30bf84b7b701423aa9092b3480dcfb7c9aafc9954cfc803f49f879f7f23b17d883713cf628bc29eee26b201230466d8527a359a5eebc3e500807ba9";
    const HASH_PREIMAGE_INPUTS: vector<u8> = x"01000000000000000000000000000000000000000000000000000000000000004327c5b27e5de1dd5cbe8085f170fd65d03be5b19983387108dfedebaf8d401bebb900ccd13d8d18e8303f7199950230aa04c6b94f0a0292fcc56d2eeef65503";

    #[test]
    fun test_hash_preimage_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                7,
                b"hash-preimage",
                HASH_PREIMAGE_VK,
                3,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 7, HASH_PREIMAGE_PROOF, HASH_PREIMAGE_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const QUADRATIC_VOTING_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190600000000000000b1daba79a1bee0a4020b9465b712aa15df3165075ca05ec49c51ea01c46fef0e92c1cd4f6cb3d8afe76ba7ccff6845ed4c45268e0cbd718b768281fbf8de28ad480483e1d312260d5858c7d547a1eb4b8117ab615149abb2db352ebee0a47503192939d1e6b49f585b2357f526dc1aa2c6c3bc1da3170b9fe6c1fd20776b891336407a35a75185206c2a4f1d7b07f2b6f5afd0c20f79e29775451fc82af42e02a9fd072fecd38f3ffc3670f101aa63f06e4b6b5fa5914b298640ed40f5814eae";
    const QUADRATIC_VOTING_PROOF: vector<u8> = x"fe4ce209a06d67dbecc41145879a166db2c4a7bac228a3d53cfbee5800d3ec1dd58785b42e55ef74c18c09ad447b9bdb7c5c45b0a125abc9a5e14295d793b91be312a4f7ae9c27eec52b4055ebf642fa0cf9703694750241dd31cc931acae611f91c0415abac3f4d0edd99ab7c0ea9a12dcaf472e7eead520065265e677e2c00";
    const QUADRATIC_VOTING_INPUTS: vector<u8> = x"a037c0a4aa990deb5250b36d1c4b5f61d5851c181e9963fc2212d78b3737812d640000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000006400000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_quadratic_voting_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                8,
                b"quadratic-voting",
                QUADRATIC_VOTING_VK,
                5,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 8, QUADRATIC_VOTING_PROOF, QUADRATIC_VOTING_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const ANONYMOUS_REPUTATION_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190600000000000000f0a76b03fe2f8ee0a0d13b3830915a180d0eb4ea74627eb4224132fb532b902c3d723028a04cc5be3a3a6b91228ad87354b9f2a8c8295c979b751b74f257f6126761e55aa0f2c1bcbf6078eb9279ea243675f00365b7d518e7a6f9702cdc51034911c68ee3ad4a3dd0546f85fe3e2fb9cddb555efd10f3ef4c8990ceb572c2840234c5e10a86c019503f0007d1152f75f393da55add952b24631c5ee9010bd0bb617ec8a08a4e4b543f84442d4faeb7647e4da67486e03ddd1de2abb19d4f099";
    const ANONYMOUS_REPUTATION_PROOF: vector<u8> = x"d5d564bbb6aa134ca819a6dc627a8e9cf59d488c1ecca6b83a6b66ef56e9961c04eb544bbabf177586b126cea376e02b132e5e00ee6051773c0200d93757ed2ab76bdfd4db144109beb0e7b12a242e487d25385493e5a030169e04a88ceb8a0162b2d19774e863c26fd314e453164d8df684691bcaf8bfd1f6632b82d7d73499";
    const ANONYMOUS_REPUTATION_INPUTS: vector<u8> = x"130b965b80480ca79e25b5cacc941c5b1de56255dc7949a4f719889e0c264a1501000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000bc020000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_anonymous_reputation_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                9,
                b"anonymous-reputation",
                ANONYMOUS_REPUTATION_VK,
                5,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 9, ANONYMOUS_REPUTATION_PROOF, ANONYMOUS_REPUTATION_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const TOKEN_SWAP_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190600000000000000e11060808970662b82da056ba48c917e681ce0115034af19f813e03c9cef2f19e24fdac60998deb4baf288d216339cfc2c1ecf8dfa8220860e064d8e43916e077baa7f7ec7f56219735422fecbf40daf9186cf02490c786e45b74aebe99ce71245a9554d6762b945b7eae776c94f275b020decaeb82f104ae85358c87785fb2d39c09ae82181d315f39a32f2f5be76f1e92ae1d36d949c106eaef155e9daf58d48236f963113147690024c53983b4cef0daa74a239a89a08b9ad6f7c01ed4d9e";
    const TOKEN_SWAP_PROOF: vector<u8> = x"a4e0308fce282ec002dd67295486a6c02f87689110a1aa3859b8200b90d21402db954952e46e9ca9d04d19e183e7303ce1756deba96d2eefac1acc073090340b47217a942c9641838720278145a689064c8742162af7fd35ef7866093ad6cd97a88a6290097c4555eb11c3ed1e7990ca574f7679a294b8ea50f476c1c6d19201";
    const TOKEN_SWAP_INPUTS: vector<u8> = x"0100000000000000000000000000000000000000000000000000000000000000143ac15782be3da2864e1dada2bc2c30370c248e42de20caaebfef7a4c7a350ca086010000000000000000000000000000000000000000000000000000000000dc050000000000000000000000000000000000000000000000000000000000008c00000000000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_token_swap_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                10,
                b"token-swap",
                TOKEN_SWAP_VK,
                5,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 10, TOKEN_SWAP_PROOF, TOKEN_SWAP_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const PATIENCE_PROOF_VK: vector<u8> = x"3cb243e5f06bd40f0ef0956afe9225898cc677dc2ca58cedd3e1d92c8bb78a2643d391fc7c91ea12ba2683e7b5535e677a2f9429cc7e161ea5d4ed65923cba0457d943284ca3f3e3e1f26d68e0e462f6d602f51ce336d4b276e9acb8aa2435adedf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190500000000000000e5e24f27517a6e35678697d7b68230477193b66fa036c0ed478f8a88e46985a6c2a1cb3b9babf83b9f21a1613c0b59b23fb885c20591180acab3aa88dd9212aa0a0d746fd8076021f547099a67adbe4e4b2b89e527ef230af03e56d45f6ff9a50d942eb9a34b9b8a2646c92e5162963a42f2d8e1b36a1dfd8593029b8dcd8f82cbebad861c9a0a0540599afee40140d56d012d94adb0a5535560e18361ce3d1f";
    const PATIENCE_PROOF_PROOF: vector<u8> = x"b54b85d43804675fc41e5dcf0155ccad7d8b57f292f33d1a2ab1bb10c659ba16250bc69659b26c513e8486516b94212c89a53650c2dd81d68b4d5a4c24a73c0ac6c0d384fc790c6284332ffb2960562ea4586b276764bfbc8b2b739570a423a89eea2e873a5ca79d2d4e9f0a22b4fba93a62c8a7154ee5d00c058204de76610f";
    const PATIENCE_PROOF_INPUTS: vector<u8> = x"0100000000000000000000000000000000000000000000000000000000000000283d420002cbb76031123f9477a04a3fdf1ef044938c7c36a7993d6bbf656400100e0000000000000000000000000000000000000000000000000000000000009c5be892bb0c424b854092effff77a6ff189c48f31da1e221d3d50589ad52d29";

    #[test]
    fun test_patience_proof_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                11,
                b"patience-proof",
                PATIENCE_PROOF_VK,
                4,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 11, PATIENCE_PROOF_PROOF, PATIENCE_PROOF_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }

    const SIGNATURE_VERIFICATION_VK: vector<u8> = x"16089f9dbc7a13840b55785b4691804242826600d9cd81586ced01c894139221db0d96c3bacd942724d9261e59c02b587441112f6cb63c9f30ed886df399fa08a1891e84ce2930ea3c30e5d193e3b8248e5d080e8f54a5fee9753d567c6b2a95edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e19edf692d95cbdde46ddda5ef7d422436779445c5e66006a42761e1f12efde0018c212f3aeb785e49712e7a9353349aaf1255dfb31b7bf60723a480d9293938e190400000000000000cc2a61a1acdc9d49324521dbed6217e7d42a1097630d50acf108232b4412d80b1c031567d2d91dbc8e33fd8bc60e453aae236d480fb402fff644f8cd173367a95cbcc75c4f8174720ac1eab7478e6a9b5c3fe5109304895802486f636c0aaf27ec59143b2635caed1932b251e1434e44f1d5c5637cebb6c480e27ea00601cb2c";
    const SIGNATURE_VERIFICATION_PROOF: vector<u8> = x"811b78512d293d47721c08d0de98f34dc8f7ff31c11abc84fc5428b4d9624825a3a887fd7d400832802cb7cc40cafd288e066c58ce4460dea246ea565a157b01e3ce6dbee74ee48dc74cdfe1d314b08a5ac7c5a0d3e3e41f15427a0b9dec6a11204188c135c88f072e92e6da943600296c030dc593e30bb4a93fc16835d25990";
    const SIGNATURE_VERIFICATION_INPUTS: vector<u8> = x"d95fc7120d026ba73a9ebd86057d015c64d8eada769c069d776ba04deb70490da0218f3d98b49fbdf800812aba4735638c09fb0fbffa1f8b4fd264db233bbb17d202964900000000000000000000000000000000000000000000000000000000";

    #[test]
    fun test_signature_verification_real_proof() {
        let mut scenario = test_scenario::begin(ADMIN);
        { groth16_verifier::init_for_testing(scenario.ctx()); };
        scenario.next_tx(ADMIN);
        {
            let mut registry = scenario.take_shared<VerifierRegistry>();
            let admin_cap = scenario.take_from_sender<AdminCap>();
            groth16_verifier::register_circuit(
                &admin_cap,
                &mut registry,
                12,
                b"signature-verification",
                SIGNATURE_VERIFICATION_VK,
                3,
            );
            let ok = groth16_verifier::verify_proof_static(
                &registry, 12, SIGNATURE_VERIFICATION_PROOF, SIGNATURE_VERIFICATION_INPUTS,
            );
            assert!(ok);
            test_scenario::return_to_sender(&scenario, admin_cap);
            test_scenario::return_shared(registry);
        };
        scenario.end();
    }
}
