import chalk from 'chalk';
import ora from 'ora';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import { TEMPLATES } from '../templates';

export async function createCircuit(name: string, templateName?: string) {
  const spinner = ora();

  console.log(chalk.cyan('\n🔷 zkRune Circuit Creator\n'));

  // If no template specified, ask user
  if (!templateName) {
    const { selectedTemplate } = await inquirer.prompt([
      {
        type: 'list',
        name: 'selectedTemplate',
        message: 'Select a template:',
        choices: Object.keys(TEMPLATES).map(key => ({
          name: `${TEMPLATES[key].name} - ${TEMPLATES[key].description}`,
          value: key,
        })),
      },
    ]);
    templateName = selectedTemplate;
  }

  if (!templateName || !TEMPLATES[templateName]) {
    throw new Error(`Template "${templateName || 'unknown'}" not found. Run "zkrune templates" to see available templates.`);
  }

  const template = TEMPLATES[templateName];

  spinner.start(`Creating circuit "${name}" from template "${template.name}"...`);

  // Create project directory
  const projectDir = path.join(process.cwd(), name);

  if (await fs.pathExists(projectDir)) {
    spinner.fail();
    throw new Error(`Directory "${name}" already exists`);
  }

  await fs.ensureDir(projectDir);

  // Copy template files
  await fs.writeFile(
    path.join(projectDir, `${name}.circom`),
    template.circuit
  );

  // Create sample input
  await fs.writeFile(
    path.join(projectDir, 'input.json'),
    JSON.stringify(template.sampleInput, null, 2)
  );

  // Create README
  const readme = `# ${name}

Template: **${template.name}**

${template.description}

## Usage

### Compile
\`\`\`bash
zkrune compile ${name}.circom
\`\`\`

### Test
\`\`\`bash
zkrune test ${name} --input input.json
\`\`\`

## Template Info

**Category:** ${template.category}
**Difficulty:** ${template.difficulty}

${template.useCases ? `### Use Cases\n${template.useCases.map((uc: string) => `- ${uc}`).join('\n')}` : ''}

---

Generated by zkRune CLI
https://zkrune.com
`;

  await fs.writeFile(path.join(projectDir, 'README.md'), readme);

  spinner.succeed(chalk.green(`Circuit "${name}" created successfully!`));

  console.log(chalk.dim('\nFiles created:'));
  console.log(chalk.dim(`  📁 ${name}/`));
  console.log(chalk.dim(`    ├── ${name}.circom`));
  console.log(chalk.dim(`    ├── input.json`));
  console.log(chalk.dim(`    └── README.md`));

  console.log(chalk.cyan('\nNext steps:'));
  console.log(chalk.white(`  cd ${name}`));
  console.log(chalk.white(`  zkrune compile ${name}.circom`));
  console.log('');
}

