/**
 * Whale-chat token registry.
 *
 * Each entry binds a token mint to its display label, threshold, snapshot
 * URL (static file in /public, generated by scripts/snapshot-holders.ts),
 * and Telegram invite link. The whale-chat page renders the same UI for
 * any entry — only this config differs.
 */

export interface WhaleTokenConfig {
  /** url-safe key, used in route paths and snapshot suffix */
  key: string;
  mint: string;
  decimals: number;
  symbol: string;
  name: string;
  /** total supply in whole-token units (not raw) — for threshold UI hints */
  supplyTotal: number;
  /** threshold in whole-token units — proof must show balance >= this */
  threshold: number;
  /** % of supply at threshold (display only) */
  thresholdPercent: number;
  /** path to static snapshot file under /public — served by Vercel */
  snapshotUrl: string;
  /** telegram invite link shown post-verification */
  telegramLink: string;
  /** Tailwind accent color class — picks page primary tint (optional) */
  accentClass?: string;
}

export const WHALE_TOKENS: Record<string, WhaleTokenConfig> = {
  zkrune: {
    key: 'zkrune',
    mint: '51mxznNWNBHh6iZWwNHBokoaxHYS2Amds1hhLGXkpump',
    decimals: 6,
    symbol: 'zkRUNE',
    name: 'zkRune',
    supplyTotal: 1_000_000_000,
    threshold: 10_000_000,
    thresholdPercent: 1,
    snapshotUrl: '/snapshot.json',
    telegramLink: process.env.NEXT_PUBLIC_WHALE_CHAT_LINK ?? '',
  },
};

export function getWhaleToken(key: string): WhaleTokenConfig | null {
  return WHALE_TOKENS[key] ?? null;
}