/**
 * Issuer-side helpers for the rwa-eligibility circuit.
 *
 * The flow this supports:
 *
 *   1. The holder generates a subject secret and derives a commitment from it.
 *      The secret never leaves the holder; the issuer only ever sees the
 *      commitment, which is why a breach of the issuer's records does not
 *      yield usable credentials and why the issuer cannot impersonate its own
 *      investors.
 *
 *   2. The issuer signs a claim about that commitment — tier, jurisdiction and
 *      validity window — with EdDSA over Poseidon.
 *
 *   3. A venue publishes the jurisdictions it serves as a Merkle root and
 *      configures the issuer public keys it trusts.
 *
 *   4. The holder proves, in zero knowledge, that a trusted issuer signed a
 *      credential over a commitment they can open, that the tier clears the
 *      offering's bar, that the country is on the venue's list, and that the
 *      credential is currently valid.
 */

import { buildEddsa, buildPoseidon } from 'circomlibjs';

/**
 * Accreditation tiers, ordered so that a numeric >= comparison expresses
 * "clears this bar". A qualified purchaser entering an accredited-investor
 * offering proves tier >= 2 without disclosing that they are a 3.
 */
export const ACCREDITATION_TIERS = {
  /** No accreditation on file. Present so a tier is never absent. */
  NONE: 0,
  /** Passed KYC/AML but not accredited. */
  KYC_CLEARED: 1,
  /** Accredited investor (e.g. SEC Rule 501). */
  ACCREDITED: 2,
  /** Qualified purchaser (e.g. Investment Company Act s.2(a)(51)). */
  QUALIFIED_PURCHASER: 3,
  /** Institutional counterparty. */
  INSTITUTIONAL: 4,
} as const;

export type AccreditationTier =
  (typeof ACCREDITATION_TIERS)[keyof typeof ACCREDITATION_TIERS];

/** Domain tag mixed into jurisdiction leaves so a leaf is never readable as an internal node. */
const JURISDICTION_LEAF_TAG = 1n;

/** Depth of the jurisdiction allowlist tree. Must match the circuit. */
export const JURISDICTION_TREE_DEPTH = 10;

export interface IssuerKeypair {
  /** Keep private. Signs credentials. */
  privateKey: Uint8Array;
  /** Publish. Verifiers configure this as their trust anchor. */
  publicKey: { Ax: string; Ay: string };
}

export interface CredentialClaim {
  subjectCommitment: string;
  accreditationTier: number;
  jurisdictionCode: number;
  issuedAt: number;
  expiresAt: number;
}

export interface SignedCredential extends CredentialClaim {
  signature: { R8x: string; R8y: string; S: string };
}

let poseidonPromise: Promise<any> | null = null;
let eddsaPromise: Promise<any> | null = null;

function getPoseidon() {
  poseidonPromise ??= buildPoseidon();
  return poseidonPromise;
}

function getEddsa() {
  eddsaPromise ??= buildEddsa();
  return eddsaPromise;
}

/**
 * Derives the commitment the holder hands to the issuer.
 *
 * The secret must be generated by the holder and kept by the holder. Anyone
 * who learns it can prove eligibility as that holder.
 */
export async function subjectCommitment(subjectSecret: bigint): Promise<string> {
  const poseidon = await getPoseidon();
  return poseidon.F.toObject(poseidon([subjectSecret])).toString();
}

/** Generates a fresh issuer keypair. The private key must never be published. */
export async function createIssuerKeypair(
  privateKey: Uint8Array,
): Promise<IssuerKeypair> {
  const eddsa = await getEddsa();
  const pub = eddsa.prv2pub(privateKey);
  return {
    privateKey,
    publicKey: {
      Ax: eddsa.F.toObject(pub[0]).toString(),
      Ay: eddsa.F.toObject(pub[1]).toString(),
    },
  };
}

/**
 * The message the issuer signs. Every field the circuit enforces feeds this
 * hash, so altering any one of them after issuance invalidates the signature.
 */
export async function credentialHash(claim: CredentialClaim): Promise<bigint> {
  const poseidon = await getPoseidon();
  return poseidon.F.toObject(
    poseidon([
      BigInt(claim.subjectCommitment),
      BigInt(claim.accreditationTier),
      BigInt(claim.jurisdictionCode),
      BigInt(claim.issuedAt),
      BigInt(claim.expiresAt),
    ]),
  );
}

/** Signs a claim. This is the issuer attesting; zkRune only verifies the attestation. */
export async function issueCredential(
  issuer: IssuerKeypair,
  claim: CredentialClaim,
): Promise<SignedCredential> {
  const eddsa = await getEddsa();
  const message = await credentialHash(claim);
  const signature = eddsa.signPoseidon(issuer.privateKey, eddsa.F.e(message));
  return {
    ...claim,
    signature: {
      R8x: eddsa.F.toObject(signature.R8[0]).toString(),
      R8y: eddsa.F.toObject(signature.R8[1]).toString(),
      S: signature.S.toString(),
    },
  };
}

export interface JurisdictionAllowlist {
  root: string;
  /** Proof of inclusion for one accepted country code. */
  pathFor(jurisdictionCode: number): { pathElements: string[]; pathIndices: string[] };
}

/**
 * Builds the venue's allowlist of jurisdictions as a Merkle tree.
 *
 * This is an allowlist, not a denylist: proving a value is absent from a set
 * needs a different construction, so a venue states the countries it serves
 * rather than the ones it excludes.
 */
export async function buildJurisdictionAllowlist(
  jurisdictionCodes: number[],
  depth: number = JURISDICTION_TREE_DEPTH,
): Promise<JurisdictionAllowlist> {
  const poseidon = await getPoseidon();
  const F = poseidon.F;
  const hash2 = (a: bigint, b: bigint) => F.toObject(poseidon([a, b]));

  const capacity = 2 ** depth;
  if (jurisdictionCodes.length > capacity) {
    throw new Error(
      `${jurisdictionCodes.length} jurisdictions exceed the ${capacity}-leaf capacity of a depth-${depth} tree`,
    );
  }

  const unique = [...new Set(jurisdictionCodes)].sort((a, b) => a - b);
  const leaves: bigint[] = unique.map((code) =>
    hash2(JURISDICTION_LEAF_TAG, BigInt(code)),
  );
  const indexOf = new Map(unique.map((code, i) => [code, i]));

  // Pad with zero-subtree hashes so every level is complete.
  const zeros: bigint[] = [0n];
  for (let i = 1; i <= depth; i++) zeros.push(hash2(zeros[i - 1], zeros[i - 1]));

  const levels: bigint[][] = [leaves];
  for (let level = 0; level < depth; level++) {
    const current = levels[level];
    const next: bigint[] = [];
    for (let i = 0; i < current.length; i += 2) {
      const left = current[i];
      const right = i + 1 < current.length ? current[i + 1] : zeros[level];
      next.push(hash2(left, right));
    }
    levels.push(next.length > 0 ? next : [zeros[level + 1]]);
  }

  const root = (levels[depth][0] ?? zeros[depth]).toString();

  return {
    root,
    pathFor(jurisdictionCode: number) {
      const index = indexOf.get(jurisdictionCode);
      if (index === undefined) {
        throw new Error(`jurisdiction ${jurisdictionCode} is not on this allowlist`);
      }
      const pathElements: string[] = [];
      const pathIndices: string[] = [];
      let idx = index;
      for (let level = 0; level < depth; level++) {
        const current = levels[level];
        const siblingIndex = idx % 2 === 0 ? idx + 1 : idx - 1;
        const sibling =
          siblingIndex < current.length ? current[siblingIndex] : zeros[level];
        pathElements.push(sibling.toString());
        pathIndices.push(String(idx % 2));
        idx = Math.floor(idx / 2);
      }
      return { pathElements, pathIndices };
    },
  };
}

/** Assembles the witness input for the rwa-eligibility circuit. */
export function buildCircuitInput(params: {
  subjectSecret: bigint;
  credential: SignedCredential;
  issuerPublicKey: { Ax: string; Ay: string };
  jurisdictionPath: { pathElements: string[]; pathIndices: string[] };
  jurisdictionRoot: string;
  requiredTier: number;
  currentTime: number;
  policyId: string;
  sessionNonce: string;
}): Record<string, string | string[]> {
  const { credential: c } = params;
  return {
    subjectSecret: params.subjectSecret.toString(),
    accreditationTier: String(c.accreditationTier),
    jurisdictionCode: String(c.jurisdictionCode),
    issuedAt: String(c.issuedAt),
    expiresAt: String(c.expiresAt),
    issuerR8x: c.signature.R8x,
    issuerR8y: c.signature.R8y,
    issuerS: c.signature.S,
    jurisdictionPathElements: params.jurisdictionPath.pathElements,
    jurisdictionPathIndices: params.jurisdictionPath.pathIndices,
    issuerAx: params.issuerPublicKey.Ax,
    issuerAy: params.issuerPublicKey.Ay,
    currentTime: String(params.currentTime),
    requiredTier: String(params.requiredTier),
    jurisdictionRoot: params.jurisdictionRoot,
    policyId: params.policyId,
    sessionNonce: params.sessionNonce,
  };
}
