/**
 * Regenerates generated_vk.rs from the current verification_key.json files.
 * Only updates the 5 circuits that were recompiled; others are left as-is.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '../..');

const CIRCUITS = [
  { name: 'age-verification',      id: 0  },
  { name: 'balance-proof',         id: 1  },
  { name: 'membership-proof',      id: 2  },
  { name: 'credential-proof',      id: 3  },
  { name: 'private-voting',        id: 4  },
  { name: 'nft-ownership',         id: 5  },
  { name: 'range-proof',           id: 6  },
  { name: 'hash-preimage',         id: 7  },
  { name: 'quadratic-voting',      id: 8  },
  { name: 'anonymous-reputation',  id: 9  },
  { name: 'token-swap',            id: 10 },
  { name: 'patience-proof',        id: 11 },
  { name: 'signature-verification',id: 12 },
];

/**
 * Convert a snarkjs G1 point [x, y] to Light Protocol 64-byte big-endian format.
 * snarkjs stores Montgomery-form decimal strings; we convert to 32-byte BE each.
 */
function g1ToBytes(point) {
  const x = BigInt(point[0]);
  const y = BigInt(point[1]);
  return [x, y].map(n => {
    const hex = n.toString(16).padStart(64, '0');
    const bytes = [];
    for (let i = 0; i < 64; i += 2) bytes.push(parseInt(hex.slice(i, i + 2), 16));
    return bytes;
  }).flat();
}

/**
 * Convert a snarkjs G2 point [[c0x, c1x], [c0y, c1y]] to 128-byte format.
 * Light Protocol uses: [c1 BE | c0 BE] ordering (reversed from bn128 convention).
 */
function g2ToBytes(point) {
  // point = [[c0_x, c1_x], [c0_y, c1_y]]
  const coordsToBytes = (pair) => {
    const c0 = BigInt(pair[0]);
    const c1 = BigInt(pair[1]);
    // Light Protocol ordering: c1 first, then c0
    return [c1, c0].map(n => {
      const hex = n.toString(16).padStart(64, '0');
      const bytes = [];
      for (let i = 0; i < 64; i += 2) bytes.push(parseInt(hex.slice(i, i + 2), 16));
      return bytes;
    }).flat();
  };
  return [...coordsToBytes(point[0]), ...coordsToBytes(point[1])];
}

function toHexArray(bytes, indent = '    ') {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 8) {
    const chunk = bytes.slice(i, i + 8).map(b => `0x${b.toString(16).padStart(2, '0')}`).join(', ');
    lines.push(`${indent}${chunk},`);
  }
  return lines.join('\n');
}

function toConstName(name) {
  return name.toUpperCase().replace(/-/g, '_');
}

function generateVKRust(vkJson, constName) {
  const alpha = g1ToBytes(vkJson.vk_alpha_1);
  const beta  = g2ToBytes(vkJson.vk_beta_2);
  const gamma = g2ToBytes(vkJson.vk_gamma_2);
  const delta = g2ToBytes(vkJson.vk_delta_2);
  const ic    = vkJson.IC.map(p => g1ToBytes(p));
  const nPublic = ic.length - 1; // IC[0] is the constant term

  let out = `// Auto-generated verification key for ${constName.replace(/_/g, ' ')}\n`;
  out += `// nPublic: ${nPublic}\n\n`;

  out += `pub const ${constName}_VK_ALPHA_G1: [u8; 64] = [\n${toHexArray(alpha)}\n];\n\n`;
  out += `pub const ${constName}_VK_BETA_G2: [u8; 128] = [\n${toHexArray(beta)}\n];\n\n`;
  out += `pub const ${constName}_VK_GAMMA_G2: [u8; 128] = [\n${toHexArray(gamma)}\n];\n\n`;
  out += `pub const ${constName}_VK_DELTA_G2: [u8; 128] = [\n${toHexArray(delta)}\n];\n\n`;

  out += `pub const ${constName}_VK_IC: [[u8; 64]; ${ic.length}] = [\n`;
  ic.forEach((p, i) => {
    out += `    // IC[${i}]\n    [\n${toHexArray(p, '        ')}\n    ],\n`;
  });
  out += `];\n`;

  out += `pub const ${constName}_VK: Groth16Verifyingkey = Groth16Verifyingkey {\n`;
  out += `    nr_pubinputs: ${nPublic},\n`;
  out += `    vk_alpha_g1: ${constName}_VK_ALPHA_G1,\n`;
  out += `    vk_beta_g2: ${constName}_VK_BETA_G2,\n`;
  out += `    vk_gamme_g2: ${constName}_VK_GAMMA_G2,\n`;
  out += `    vk_delta_g2: ${constName}_VK_DELTA_G2,\n`;
  out += `    vk_ic: &${constName}_VK_IC,\n`;
  out += `};\n`;

  return out;
}

// Build the full file
let rustCode = `// Auto-generated by zkRune converter\n`;
rustCode += `// DO NOT EDIT - regenerate with: node lib/solana/generateRustVK.mjs\n\n`;
rustCode += `use groth16_solana::groth16::Groth16Verifyingkey;\n\n`;

for (const circuit of CIRCUITS) {
  const vkPath = join(ROOT, 'circuits', circuit.name, 'verification_key.json');
  if (!existsSync(vkPath)) {
    console.warn(`⚠  Skipping ${circuit.name} — verification_key.json not found`);
    continue;
  }
  const vkJson = JSON.parse(readFileSync(vkPath, 'utf-8'));
  const constName = toConstName(circuit.name);
  console.log(`✓ ${circuit.name} (ID ${circuit.id})`);
  rustCode += generateVKRust(vkJson, constName);
  rustCode += '\n';
}

// get_vk_by_id helper
rustCode += `/// Get verifying key by template ID\n`;
rustCode += `pub fn get_vk_by_id(template_id: u8) -> Option<&'static Groth16Verifyingkey<'static>> {\n`;
rustCode += `    match template_id {\n`;
for (const circuit of CIRCUITS) {
  rustCode += `        ${circuit.id} => Some(&${toConstName(circuit.name)}_VK),\n`;
}
rustCode += `        _ => None,\n    }\n}\n`;

const outPath = join(ROOT, 'solana-groth16-verifier/src/generated_vk.rs');
writeFileSync(outPath, rustCode);
console.log(`\n✅ Written to: ${outPath}`);
