/**
 * Generate Rust verification key code from snarkjs VK for ALL circuits
 * Run: npx ts-node lib/solana/generateRustVK.ts
 */

import * as fs from 'fs';
import * as path from 'path';
import { convertVKForSolana, generateRustVK } from './converter';

// All circuit names with their template IDs
const CIRCUITS = [
  { name: 'age-verification', id: 0 },
  { name: 'balance-proof', id: 1 },
  { name: 'membership-proof', id: 2 },
  { name: 'credential-proof', id: 3 },
  { name: 'private-voting', id: 4 },
  { name: 'nft-ownership', id: 5 },
  { name: 'range-proof', id: 6 },
  { name: 'hash-preimage', id: 7 },
  { name: 'quadratic-voting', id: 8 },
  { name: 'anonymous-reputation', id: 9 },
  { name: 'token-swap', id: 10 },
  { name: 'patience-proof', id: 11 },
  { name: 'signature-verification', id: 12 },
];

function toConstName(circuitName: string): string {
  return circuitName.toUpperCase().replace(/-/g, '_');
}

const outputPath = path.join(__dirname, '../../solana-groth16-verifier/src/generated_vk.rs');

let rustCode = `// Auto-generated by zkRune converter
// DO NOT EDIT - regenerate with: npx ts-node lib/solana/generateRustVK.ts

use groth16_solana::groth16::Groth16Verifyingkey;

`;

console.log('Generating VKs for all circuits...\n');

for (const circuit of CIRCUITS) {
  const vkPath = path.join(__dirname, `../../circuits/${circuit.name}/verification_key.json`);
  
  if (!fs.existsSync(vkPath)) {
    console.log(`⚠️  Skipping ${circuit.name} - verification_key.json not found`);
    continue;
  }
  
  console.log(`✓ Processing ${circuit.name} (ID: ${circuit.id})`);
  
  const vkJson = JSON.parse(fs.readFileSync(vkPath, 'utf-8'));
  const constName = toConstName(circuit.name);
  
  // Use G2 variant 1 = Light Protocol format: [c0 BE, c1 BE]
  const solanaVK = convertVKForSolana(vkJson, 1);
  
  // Generate const arrays
  rustCode += generateRustVK(solanaVK, constName);
  rustCode += '\n';
  
  // Generate Groth16Verifyingkey struct
  rustCode += `pub const ${constName}_VK: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${solanaVK.nPublic},
    vk_alpha_g1: ${constName}_VK_ALPHA_G1,
    vk_beta_g2: ${constName}_VK_BETA_G2,
    vk_gamme_g2: ${constName}_VK_GAMMA_G2,
    vk_delta_g2: ${constName}_VK_DELTA_G2,
    vk_ic: &${constName}_VK_IC,
};

`;
}

// Generate helper function to get VK by template ID
rustCode += `/// Get verifying key by template ID
pub fn get_vk_by_id(template_id: u8) -> Option<&'static Groth16Verifyingkey<'static>> {
    match template_id {
`;

for (const circuit of CIRCUITS) {
  const constName = toConstName(circuit.name);
  rustCode += `        ${circuit.id} => Some(&${constName}_VK),\n`;
}

rustCode += `        _ => None,
    }
}
`;

fs.writeFileSync(outputPath, rustCode);
console.log(`\n✅ Rust VK code written to: ${outputPath}`);
console.log(`   ${CIRCUITS.length} circuits processed`);
